# -*- coding: utf-8 -*-
"""myAPP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WZX-GChNfvrDQ9zvtR1ynEWHZg9qj_Y
"""

pip install openai

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
 %%writefile app.py
 import openai
 import streamlit as st
 
 # Set the API key
 openai.api_key = "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"
 
 st.set_page_config(page_title="OpenAI Text Completion", page_icon=":guardsman:", layout="wide")
 st.title("OpenAI Text Completion")
 
 prompt = st.text_input("Enter your prompt:")
 if st.button("Generate Text"):
    completions = openai.Completion.create(engine="text-davinci-002", prompt=prompt, max_tokens=1024)
     text = completions.choices[0].text
     st.write(text)


awk ‘!/ipython/’ myAPP.py > temp.py && mv temp.py app.py && rm myAPP.py

streamlit run app.py
